#include "OpenDRTLutExporter.h"

#include <algorithm>
#include <cstddef>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <vector>

#include "OpenDRTProcessor.h"

namespace OpenDRTLut {

bool isSupportedResolution(FormatProfile profile, int resolution) {
  switch (profile) {
    case FormatProfile::GenericCube:
      return resolution == 17 || resolution == 33 || resolution == 65;
    case FormatProfile::SonyCameraCube:
      return resolution == 17 || resolution == 33;
    case FormatProfile::ArriColorToolCube:
      return resolution == 33;
  }
  return false;
}

int defaultResolution(FormatProfile profile) {
  switch (profile) {
    case FormatProfile::SonyCameraCube:
      return 33;
    case FormatProfile::ArriColorToolCube:
      return 33;
    case FormatProfile::GenericCube:
    default:
      return 33;
  }
}

const char* profileLabel(FormatProfile profile) {
  switch (profile) {
    case FormatProfile::SonyCameraCube:
      return "Sony Camera CUBE";
    case FormatProfile::ArriColorToolCube:
      return "ARRI Color Tool CUBE";
    case FormatProfile::GenericCube:
    default:
      return "CUBE";
  }
}

namespace {

std::string cleanTitle(std::string title) {
  if (title.empty()) return "ME_OpenDRT";
  for (char& c : title) {
    if (c == '"' || c == '\r' || c == '\n') c = '_';
  }
  return title;
}

}  // namespace

ExportResult writeCubeFile(const std::string& path, const OpenDRTParams& params, const ExportOptions& options) {
  ExportResult result{};
  const int size = options.resolution;
  if (!isSupportedResolution(options.profile, size)) {
    result.error = "Unsupported LUT resolution for selected profile.";
    return result;
  }
  if (path.empty()) {
    result.error = "No output path was selected.";
    return result;
  }

  const std::size_t sampleCount = static_cast<std::size_t>(size) * static_cast<std::size_t>(size) * static_cast<std::size_t>(size);
  std::vector<float> src(sampleCount * 4u, 1.0f);
  std::vector<float> dst(sampleCount * 4u, 1.0f);

  std::size_t idx = 0;
  const float denom = static_cast<float>(size - 1);
  for (int b = 0; b < size; ++b) {
    for (int g = 0; g < size; ++g) {
      for (int r = 0; r < size; ++r) {
        src[idx + 0] = static_cast<float>(r) / denom;
        src[idx + 1] = static_cast<float>(g) / denom;
        src[idx + 2] = static_cast<float>(b) / denom;
        src[idx + 3] = 1.0f;
        idx += 4u;
      }
    }
  }

  OpenDRTProcessor processor(params);
  const size_t rowBytes = sampleCount * 4u * sizeof(float);
  if (!processor.renderCPUReference(src.data(), dst.data(), static_cast<int>(sampleCount), 1, rowBytes, rowBytes)) {
    result.error = "CPU reference transform failed while generating LUT.";
    return result;
  }

  std::ofstream os(path, std::ios::binary | std::ios::trunc);
  if (!os.is_open()) {
    result.error = "Could not open output file for writing.";
    return result;
  }

  os << "TITLE \"" << cleanTitle(options.title) << "\"\n";
  os << "# Generated by ME_OpenDRT\n";
  os << "# Profile: " << profileLabel(options.profile) << "\n";
  if (!options.comment.empty()) {
    std::istringstream lines(options.comment);
    std::string line;
    while (std::getline(lines, line)) {
      os << "# " << line << "\n";
    }
  }
  os << "DOMAIN_MIN 0.0 0.0 0.0\n";
  os << "DOMAIN_MAX 1.0 1.0 1.0\n";
  os << "LUT_3D_SIZE " << size << "\n";
  os << std::fixed << std::setprecision(9);

  for (std::size_t i = 0; i < sampleCount; ++i) {
    const std::size_t o = i * 4u;
    os << dst[o + 0] << ' ' << dst[o + 1] << ' ' << dst[o + 2] << "\n";
  }
  if (!os.good()) {
    result.error = "Failed while writing LUT data.";
    return result;
  }

  result.ok = true;
  return result;
}

}  // namespace OpenDRTLut
